### ISSUE TITLE
HPSS path is not flexible when extracting archived files

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/zstash#11]
The extract command ignores the HPSS path passed to it and still looks for archived files at the HPSS path used in the create command.

I noticed this because I renamed my HPSS directory from ACME to E3SM. When extracting, it still tries to find the archive under the ACME directory.

Can we use the HPSS path supplied to the extract command instead of the original one?

**Comment by zshaheen** [comment]
@tangq This was fixed in the latest code on master. Try that and let me know if it works for you.

**Comment by zshaheen** [comment]
After talking to @tangq in person about this, this issue seems resolved. Feel free to open it if something is wrong.
