### ISSUE TITLE
unable to extract or list user_nl_* files

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/zstash#111]
When I try and list out all the user_nl files I only see the user_nl_cam
```
[14:08:48] >> zstash ls --hpss=none case_scripts/user_*
case_scripts/user_nl_cam
```

But when I open the index.db manually and list out the namelist files I get the complete list
```
[14:08:52] >> sqlite3 zstash/index.db
SQLite version 3.34.0 2020-12-01 16:14:00
Enter ".help" for usage hints.
sqlite> select name from files where name like "%user_nl%";
case_scripts/user_nl_cam
case_scripts/user_nl_clm
case_scripts/user_nl_cpl
case_scripts/user_nl_mosart
case_scripts/user_nl_mpascice
case_scripts/user_nl_mpaso
```

**Comment by golaz** [comment]
@sterlingbaldwin : when using zstash ls or extract with wildcards, please make sure to enclose your expression in double quotes:

`zstash ls --hpss=none "case_scripts/user_*"`

This will prevent the shell from performing a substitution before passing the arguments to zstash.

**Comment by golaz** [comment]
See also https://github.com/E3SM-Project/zstash/issues/96

**Comment by sterlingbaldwin** [comment]
Thanks @golaz, I had no idea why it was failing, but wrapping the zstash glob in quotes so the OS doesnt try and interpret them makes sense.
