### ISSUE TITLE
Add support for checking of local, extracted files

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/zstash#13]
If you run `zstash check` or even `zstash extract`, it'll work with tars that were previously downloaded. We want to use this on the extracted files from these tars as well. Maybe do this via an `--check_extracted_files` parameter or something similar.

This will be especially useful when fixing [the broken files for the v1 DECK output](https://acme-climate.atlassian.net/wiki/spaces/SIM/pages/668959422/v1+DECK+output+HPSS+archive). We'll recreate the files by running the model again, and check these new files against what we had previously. If all is good, we can proceed with uploading the fixed data.

**Comment by golaz** [comment]
@zshaheen : I don't think I fully understand how this would work... Did you mean something like:

- We could have a new `zstash verify` functionality that would do a `zstash check` and additionally check the md5 of the **local input files**? Or maybe simply `zstash check --check_local_files` or `zstash check --verify`.
- For `zstash extract`, I assume what you want to do is compute the md5 of the **newly extracted files**? `zstash extract --check_local_files` or maybe `zstash extract --verify`.

**Comment by zshaheen** [comment]
@golaz, I was referring to the first point you had, the checking of local, **extracted** files. My inclusion of `zstash extract` was probably confusing, this is only for `zstash check` and it's functionality.

**Comment by golaz** [comment]
We should implement this as  `zstash extract --verify`: full `zstash check` with an additional check against local files.

**Comment by golaz** [comment]
The 'zstash check' functionality appears to be sufficient for now. Closing.
