### ISSUE TITLE
Refactor `con` and `cur` variables from global to function arg

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/zstash#134]
The `con` and `cur` variables are only used in one function for each file that it exists in (`create.py`, `extract.py`, `ls.py`, and `update.py`), but is declared as a `global`.

```
   global con, cur
    con = sqlite3.connect(get_db_filename(cache), detect_types=sqlite3.PARSE_DECLTYPES)
    cur = con.cursor()
```

I also noticed some repeated logic involving database work. It might be better to declare the `con` and `cur` variables in `main.py` and pass them into each of the functions as an argument, rather than instantiating new `con` and `cur` variables in each function. I haven't looked too closely at those files to analyze the logic though, just a quick glance.

https://github.com/E3SM-Project/zstash/blob/master/zstash/main.py#L51
```
    if args.command == 'version':
        print(__version__)
    elif args.command == 'create':
        create()
    elif args.command == 'update':
        update()
    elif args.command == 'extract':
        extract()
    elif args.command == 'chgrp':
        chgrp()
    elif args.command == 'check':
        check()
    elif args.command == 'ls':
        ls()
    else:
        print('Unrecognized command')
        parser.print_help()
        sys.exit(1)
```

**Comment by forsyth2** [comment]
I imagine at least some of this will be addressed as part of #138
