### ISSUE TITLE
Implement verbosity command line option

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#15]
This should be easy. Implement a new command line option to control verbosity of zstash (i.e. select between INFO, DEBUG, etc.).

**Comment by zshaheen** [comment]
When doing so, I might add a new level underneath `DEBUG` for some of the parallel debugging functionality. Mainly, it would be for the below statement in `extract.py` which prints what each worker is doing.

```python
if multiprocess_worker:
    print('{} is {} {} from {}'.format(multiprocess_worker, cmd, file[1], file[5]))
```

**Comment by golaz** [comment]
Done in 9814be8693f6ab2388601d42634f0f9f2d545677
