### ISSUE TITLE
The python package includes the `tests` directory 

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/zstash#159]
The line:
https://github.com/E3SM-Project/zstash/blob/e2b1ab3166e468e7a0813c84a56032e7becbb6ec/setup.py#L9
seems designed to exclude tests but it doesn't actually have the `tests` directory in its excludes.  As a result, it ends up in the conda package and it conflicts with other packages that make the same mistake (e.g. `zppy`).

Instead, it would be much cleaner and safer to do:
```
packages=find_packages(include=['zstash', 'zstash.*'])
```

**Comment by forsyth2** [comment]
@xylar This fix causes the following error in the build https://github.com/E3SM-Project/zstash/pull/157/checks?check_run_id=3000885820: `ModuleNotFoundError: No module named 'tests'`

**Comment by xylar** [comment]
@forsyth2, I'm not familiar with how your testing works but if it relies on `tests` being a part of the python package you're creating, that isn't a good thing.  Your `zstash` (and `zppy` and `e3sm_diags`) package is actually adding a `tests` python package to the conda environment, which it shouldn't be doing.  Either you need to move the `tests` package to be within the `zstash` package or you need to modify your testing run out of the local clone of the repository where `tests` exists, or you need to copy the `tests` directory to wherever you are staging things.  I can look further at your tests if you, @tomvothecoder and @chengzhuzhang can't figure this out but I don't know too much about how your testing works so it would take me awhile to get up to speed.

**Comment by tomvothecoder** [comment]
@forsyth2 @xylar Pushed a change to the `fixes-for-rc2` branch to fix the build workflow not finding the `tests` module for local imports specific to `tests` directory.

Before:
https://github.com/E3SM-Project/zstash/blob/e2b1ab3166e468e7a0813c84a56032e7becbb6ec/.github/workflows/build_workflow.yml#L48-L51

After:
```
      - name: Run Tests
        run: |
          python -m unittest tests/test_*.py
```

**Comment by forsyth2** [comment]
I made the same fix for `zppy` and the build passed (https://github.com/E3SM-Project/zppy/issues/94, https://github.com/E3SM-Project/zppy/pull/81). I notice `zppy` doesn't include any `import tests` or `from tests` lines but `zstash` does.

@tomvothecoder Thanks, I'll take a look at the file paths.

**Comment by forsyth2** [comment]
@tomvothecoder Ok looks like that fixes it, thanks! https://github.com/E3SM-Project/zstash/pull/157/checks?check_run_id=3001257643

**Comment by xylar** [comment]
Thanks @forsyth2 and @tomvothecoder for fixing this (and the other similar issues) so quickly!
