### ISSUE TITLE
Make 'zstash extract' smarter

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#16]
Make 'zstash extract' smarter and faster. If the target file is already on disk, with the right size and modification time stamp, skip extraction. Maybe add a '--force' or '--all' option to override this new default behavior.

**Comment by zshaheen** [comment]
We can even make most commands faster by using [`hsi stage`](http://pal.mgleicher.us/HSI/hsi/hsi_reference_manual_2/hsi_commands/stage_command.html) to prefetch a tape to the cache.

**Comment by zshaheen** [comment]
When doing this, I'm **not** checking the md5 of the file on disk. But if that's needed, we can easily do that.

**Comment by zshaheen** [comment]
When getting the modified timestamp of a file, both `os.stat(file_path).st_mtime_ns` and `os.path.getmtime(file_name)` do not give the millisecond precision, unlike what's stored in the `index.db`. So we'll compare based off the seconds, which isn't the most precise metric.

**Comment by zshaheen** [comment]
@golaz, for now, both symlinks and empty dirs are extracted again, even if they are on disk. It makes the code *a little* more simple. If you do not want this, I can make sure that symlinks and empty dirs are not extracted again. The performance differential isn't that much.

**Comment by zshaheen** [comment]
> @golaz, for now, both symlinks and empty dirs are extracted again, even if they are on disk. It makes the code _a little_ more simple. If you do not want this, I can make sure that symlinks and empty dirs are not extracted again. The performance differential isn't that much.

@golaz, any input? If not, symlinks and empty dirs will be extracted. It shouldn't make much of a difference in performance or the output. But it does make the code more simple.

**Comment by zshaheen** [comment]
Done in 9eda0adabdcf9adaddf768ee80783ad98bf4f561.

**Comment by golaz** [comment]
@zshaheen: I don't see any problems extracting symlinks and empty dirs again. There is virtually no performance impact.
