### ISSUE TITLE
specify the starting tar file for checking or parallel checking

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/zstash#164]
Is it possible to specify which tar file to start the checking? Or checking multiple tar files simultaneously.

For large production runs the tar file size is huge (almost 150 TB for the 1000-year spin-up E3SMv2 NARRM run). Checking the tar files one by one can take a really long time. NERSC just had a disruption on hsi and failed my checking job. I had to recheck the files. In this case, it would be really helpful to be able to specify which tar file to start with to avoid duplicated work.

As far as I know, the zstash check job is done on 1 tar file at a time. The performance can be significantly improved if checking multiple files at once. The HPSS system normally allows retrieving multiple files simultaneously.

**Comment by tangq** [comment]
It looks like that checking multiple files is done by the option `--workers=<num of processes>`.

**Comment by tangq** [comment]
I wrote a little bash script to check the tar files one by one. The tarlist.txt contains all the tar file names (1 file name per line). Specifying the checking file names allows me to resume the checking job from the tar file where the previous job failed.

NERSC HPSS seems not stable in the past week. My zstash check job (without specifying the file name) failed multiple times. This method will be useful for this circumstance. If we add the starting file option, it will be similar to this script.

```
cat tarlist.txt | while read fn
do
  echo $fn
  zstash check --hpss=hpss_path $fn
done
```

**Comment by golaz** [comment]
@tangq: you found a very nice and easy workaround for the time being.

That being said, I think it would be very useful to have the capability of checking a subset of the tar files.

Here is a possible command line usage (similar syntax to specifying pages to print). Comma delimited list, each entry being either a single tar file or a range:

```
# Starting at 00005a until the end
zstash check --tars=00005a-
# Starting from the beginning to 00005a (included)
zstash check --tars=-00005a
# Specific range
zstash check --tars=00005a-00005c
# Selected tar files
zstash check --tars=000003e,00004e,000059
# Mix and match
zstash check --tars=0000030-000003e,00004e,00005a-

```

**Comment by golaz** [comment]
To parse the command line argument and build a list of files

- Start with empty list of tar files
- Split command line string argument  by comma into substrings
- Loop over substrings
  - Test if there is a hyphen
     - No: add tar file number to list
     - Yes: extract beginning and end range (use first or last tar file if one range is missing). Add sequence to the list.

**Comment by forsyth2** [comment]
@golaz @tangq Implementation is ready for review -- #170.
