### ISSUE TITLE
first check if all files exist

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/zstash#165]
I recently had a failing zstash check case because 1 of the files is missing on HPSS.

Can I suggest checking if all files exist in the archive as the first step of `zstash check`? This can save a lot of time if some files are missing but it may take a while to retrieve the files from HPSS before those missing files.

**Comment by tangq** [comment]
I thought the .db file will have the list of tar files. Is it? Otherwise, how does the check job know what tar files to retrieve from HPSS?

If not, it wouldn't be so helpful if it only works with `--keep` or `--hpss=none`.

**Comment by forsyth2** [comment]
If I run `zstash create` on a directory, add some more files, and run `zstash update`, then there will be two tars in the HPSS archive. If I delete one tar in the HPSS archive and run `zstash ls --hpss=<hpss-archive> --tars`, then both tars will still be listed. `zstash ls` works by reading the database file, not the actual HPSS archive's contents.

To compare the database's contents with the HPSS archive's content (the goal of this issue), we'd need to get the results of `hsi -q "ls <hpss-archive>"`, which seems quite difficult to programmatically extract information from. That is, I can run that command in the terminal, but I can't seem to get Python to get anything out of it.

@golaz Am I misunderstanding something? Is `zstash ls` supposed to list what is in the database file (current behavior) or is it intended to reflect the contents of the HPSS archive?

**Comment by golaz** [comment]
@forsyth2 : for an example on how to execute an hsi command from python, take a look at

https://github.com/E3SM-Project/zstash/blob/6b7d30ea3cc61cd1e52460838e3d6ec226cb965a/zstash/hpss.py#L73-L76

However, it looks like we will need to generalize `run_command` to optionally return stdout, not just stderr. 

https://github.com/E3SM-Project/zstash/blob/6b7d30ea3cc61cd1e52460838e3d6ec226cb965a/zstash/utils.py#L38-L55

You'll need to parse stdout to see what tar files are on HPSS. To simplify the parsing, it might be easier to do `hsi -q "ls -1 <hpss-archive>"` or `hsi -q "ls -l <hpss-archive>"`.

**Comment by golaz** [comment]
With the availability of Globus transfers directly within zstash as well the new feature to specify specific tar files to check, I think this is no longer needed.

This is an edge case that is not likely to happen very often. Changing the code for this might be over doing it.
