### ISSUE TITLE
zstash update error recovery

### ISSUE THREAD

**Issue by maltrud** [E3SM-Project/zstash#19]
my latest zstash update failed due to an I/O error:
--------
INFO: Transferring file to HPSS: zstash/000032.tar
Traceback (most recent call last):
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/bin/zstash", line 11, in <module>
    load_entry_point('zstash==0.1.0', 'console_scripts', 'zstash')()
  File "build/bdist.linux-x86_64/egg/zstash/main.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/zstash/update.py", line 146, in update
  File "build/bdist.linux-x86_64/egg/zstash/utils.py", line 85, in addfiles
sqlite3.OperationalError: disk I/O error
------------------------
it may have been a quota issue (i'm not sure), but my question is how do i recover from this?  just restart zstash update?

**Comment by golaz** [comment]
@maltrud: zstash appears to have failed when writing to the database. As you mentioned, this may be a disk quota problem. Can you point me to the directory with the zstash subdirectory so that I can take a look at the database and decide how best to recover?

**Comment by maltrud** [comment]
@golaz : /scratch3/scratchdirs/maltrud/E3SM_simulations/20181217.BCRC_CNPCTC20TR_OIBGC.ne30_oECv3.edison/archive/20181217.BCRC_CNPCTC20TR_OIBGC.ne30_oECv3.edison

**Comment by golaz** [comment]
Thanks. As I expected, the database does not include any information about the last tar file (000032.tar) because the database write failed. I want to check whether that last tar file in on HPSS, but HPSS is currently down.

I'll check again later. Remind me if you don't hear back from me.

Also, I see some unexpected sub-directories under your zstash directory:

```
cd /scratch3/scratchdirs/maltrud/E3SM_simulations/20181217.BCRC_CNPCTC20TR_OIBGC.ne30_oECv3.edison/archive/20181217.BCRC_CNPCT
C20TR_OIBGC.ne30_oECv3.edison/zstash
ls
atm  ice  index.db
```

Typically, the only thing one should see under `zstash`/ is `index.db` and possibly tar files (e.g. `000000.tar`) I'm not sure how the sub-directories `atm` and `ice` appeared and I hope you don't have anything of value in them. Although they won't cause any harm, it would be best to delete them (after you confirm there is nothing of value in there)...

**Comment by maltrud** [comment]
@golaz thanks for checking.  the atm and ice directories in the zstash dir came from when i manually extracted some files from a tar file that had reported an error, but was able to confirm the files were ok by comparing with the originals.

**Comment by golaz** [comment]
@maltrud : my suggestion for recovering. 

1. Login to hsi and delete the last tar file (000032.tar) which was not recorded in the database:
```
hsi
cd /home/m/maltrud/E3SM/20181217.BCRC_CNPCTC20TR_OIBGC.ne30_oECv3.edison/archive
rm  000032.tar
quit
```
2. Rerun `zstash update`

**Comment by maltrud** [comment]
@golaz just (hopefully) 1 more question:  the index.db file on hpss is older than my local one since zstash crashed before it could be saved.  should i remove the hpss version, or will it be ignored in the zstash update?

**Comment by golaz** [comment]
@maltrud, to be very safe, rather than delete it, you could just overwrite it with the newer one:

```
cd <your zstash dir>
hsi
cd /home/m/maltrud/E3SM/20181217.BCRC_CNPCTC20TR_OIBGC.ne30_oECv3.edison/archive
put index.db
quit
```

**Comment by maltrud** [comment]
thanks, @golaz . that is what i was planning to do--great to have confirmation.

**Comment by zshaheen** [comment]
Hi @maltrud, if this still is an issue, feel free to open it. For now, I'm closing it.

**Comment by maltrud** [comment]
@zshaheen , i talked with Qi Tang about his experiences using zstash last week.  it seems there are 2 possibly significant differences between his (and @golaz 's) and my workflow.  1) i run from edison, not dtn.  2) my output is on edison scratch, not cscratch (so i can't use dtn).  do you think these could be responsible for the many failures i had (both hpss errors and errors writing to index.db)?

**Comment by zshaheen** [comment]
Unlike Qi and Chris, I too run via Edison and not the DTNs, but I don't think that makes a difference in this case. So I'm using the same version of `hsi` that you are.

Now for very long extractions, I do run on `$CSCRATCH`. But most of the 100's of times I've tested the software, it's from my home directory. I've never seen this `sqlite3.OperationalError: disk I/O error` error before.

Like Chris suggested, have you examined your quota with `myquota`? This is something related to zstash not being able to update the`index.db` which keeps a record of which files are in which tars.

**Comment by maltrud** [comment]
i thought at first it might be related to quota (since i was way over), but even after i dropped well below quota i still got both of these errors.  all of mine were very long jobs so took a while to fail--sometimes a few hours, other times more and other times it didn't fail at all.  i wonder if you tried a very long one on edison scratch if you might find a problem.

**Comment by golaz** [comment]
@maltrud : I have successfully performed very long archiving jobs (up to several days) on NERSC DTNs with data on `$CSCRATCH`. Failures that I have experienced were related to `$CSCRATCH`, DTN or hsi going down.
