### ISSUE TITLE
support newer globus-sdk

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/zstash#196]
The constraint on globus-sdk:
https://github.com/E3SM-Project/zstash/blob/master/conda/meta.yaml#L25
has the side effect of preventing `zstash` and therefore E3SM-Unified from being installed with python 3.10.  Could you see if this constraint is necessary and, if so, what development would be required for zstash to work with the latest globus?

**Comment by xylar** [comment]
Assuming this isn't an easy fix, let's just plan on skipping python 3.10 support in E3SM-Unified for this round and hope to include it in the next version (1.7.0).  I should have anticipated these problems but decided to switch away from python 3.7 and to 3.10 relatively recently.

**Comment by forsyth2** [comment]
@xylar The `- globus-sdk >=2,<3` change was added in #188 (after `v1.2.0rc2`, before `v1.2.0rc3`). 

`v1.2.0rc2` failed to build (see https://github.com/E3SM-Project/zstash/runs/4858035601?check_suite_focus=true => `ImportError: cannot import name 'TransferAPIError' from 'globus_sdk.exc'`). @tomvothecoder determined the issue:

#154 (https://github.com/E3SM-Project/zstash/blob/master/zstash/globus.py#L11) is using `globus_sdk` v2.0.1 for importing `TransferAPIError` from `exc.py`:
https://github.com/globus/globus-sdk-python/blob/2.0.1/globus_sdk/exc.py

In the latest version of `globus_sdk` (v3.2.1),  TransferAPIError was moved to `services/transfer/errors.py`:
https://github.com/globus/globus-sdk-python/blob/3.2.1/src/globus_sdk/services/transfer/errors.py

The quick fix was to set the `globus_sdk` version range to `>=2 and <3` in `conda/meta.yaml` (as was done in #188). The recommended fix was to use the latest version of `globus_sdk` and update the code as needed. 

I'm not sure what code updates would be required to use the latest version of `globus_sdk` -- @lukaszlacinski may have more insight on this point.

**Comment by xylar** [comment]
Okay, thanks for the background.  I think this should get worked out in the next 4 months so you can support the latest `globus_sdk` but I agree that it was the right decision not to try to do that between release candidates.

**Comment by forsyth2** [comment]
Note: this *may* not require significant work. First, update all the API references and then run the tests. If nothing breaks, then the API reference updates were probably the only requirement.
