### ISSUE TITLE
Option to retry after hsi get failure

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#198]
Retrieval of tar files from HPSS on NERSC has been less reliable lately. `hsi get` occasionally fails for unknown reasons, but retrying works. We should consider adding an option to retry after a failed hsi operation.

**Comment by chengzhuzhang** [comment]
@forsyth2 The issue described in #217 seems crippled a few users..I think we may need to prioritize this feature...

**Comment by forsyth2** [comment]
@chengzhuzhang Thanks for looking into #217. I've marked this issue as high priority (for the December 2022) release -- or do you mean such high priority we should have an emergency release?

**Comment by chengzhuzhang** [comment]
Hi @forsyth2 Thank you for labeling this as high priority. I think it would be nice to have the new feature implemented and have a new release. If there will be an emergency release of e3sm-unified, we can add the new version of zstash.
