### ISSUE TITLE
Add HPSS location in log file

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/zstash#209]
I encountered this issue a few times that I couldn't remember the HPSS location of the simulation. It would be good to record the HPSS location at the beginning of the zstash log when creating the archive.

**Comment by tangq** [comment]
Good to know the `-v` option, @golaz . I will add it to my command.

**Comment by forsyth2** [comment]
@tangq We could change the logger level for the HPSS path to be `INFO` rather than `DEBUG`. Then it would print in all cases. However, I would first suggest you try out the `-v` option to see if it prints "too much info" for your needs. Thanks!

**Comment by tangq** [comment]
@forsyth2 , thanks for the suggestion. I will give it a try.

**Comment by tangq** [comment]
@forsyth2 . The `-v` option only adds about 10 lines in the log file. Not too much at all. I think we will be fine just use the `-v` option as is.

**Comment by forsyth2** [comment]
@tangq Awesome, thanks for letting us know!
