### ISSUE TITLE
Add option to work without HPSS

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#21]
E3SM dedicated machines (anvil, compy) do not have HPSS storage attached to them. It is currently up to individual users to decide on the best way to free disk space when needed. This is inefficient and could lead to unfortunate data loss.

One remedy would be to implement an option for zstash to work on systems without HPSS. This could take two forms:

1. Only create local tar archives in the zstash subdirectory. The user could then transfer tar and index.db files for offline storage.
2. Implement a remote HPSS option using globus.

The command line usage might look something like:

`zstash create --hpss=none ...` for local only

`zstash create --hpss=globus:nersc-hpss/... ...` for remote HPSS using globus.

In terms if implementation, this may be reasonably straightforward. The bulk of the changes would consist of generalizing

https://github.com/E3SM-Project/zstash/blob/master/zstash/hpss.py

to handle different backends.

**Comment by forsyth2** [comment]
Step 1 ("Only create local tar archives in the zstash subdirectory. The user could then transfer tar and index.db files for offline storage.") is resolved in #42. Step 2 ("Implement a remote HPSS option using globus.") still needs to be implemented.

**Comment by golaz** [comment]
Let's close this for now. We can open a new issue if we decide to proceed integrating Globus transfer into zstash.
