### ISSUE TITLE
v0.3 release

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#22]
Test, document, release. Ask to incorporate into E3SM unified environment.

**Comment by maltrud** [comment]
@golaz and @zshaheen when will this be available as part of e3sm_unified?

**Comment by golaz** [comment]
@maltrud, most of the enhancements should be simple to implement, but some may require a little more work (https://github.com/E3SM-Project/zstash/issues/13, https://github.com/E3SM-Project/zstash/issues/17).

It depends on how much time @zshaheen has for this, but I would expect this could be done within 2 weeks??

**Comment by xylar** [comment]
I'll go ahead an put in a placeholder for zstash in the next version of e3sm-unified.

**Comment by golaz** [comment]
Done. @zshaheen released v0.3 and @xylar incorporated in E3SM unified. Added recommendation to use E3SM unified environment on zstash documentation.
