### ISSUE TITLE
zstash check creates empty directory structure

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#24]
Minor bug that should be easily fixed. When running zstash check, zstash still creates the output directory structure. I think it's a matter of relocating if statement in extract.py near line 139:

```
                    path, name = os.path.split(fname)
                    if path != '':
                        if not os.path.isdir(path):
                            os.makedirs(path)
                    if keep_files:
                            fout = open(fname, 'w')
```

`os.makedirs(path)` should only be invoked if `keep_files` is True.

**Comment by zshaheen** [comment]
Fixed in 8c3d8b631b876c7028b2b19d2226da621f20b61b.
