### ISSUE TITLE
Question on NERSC Best Practices

### ISSUE THREAD

**Issue by matthewhoffman** [E3SM-Project/zstash#25]
In looking over https://e3sm-project.github.io/zstash/docs/html/best_practices.html , it seemed to me that a better approach on NERSC is to submit a job using zstash to the transfer queue:
https://docs.nersc.gov/filesystems/archive/#use-the-xfer-queue

Has that approach been tested?

**Comment by zshaheen** [comment]
Hi @matthewhoffman. This approach has not been tested. In fact, I think most users of zstash just run it on a login node, without submitting a batch job.

I'd guess one reason that this is recommended is to limit the number of HPSS instances to 15<sup><a href="https://docs.nersc.gov/jobs/examples/#xfer-queue">[1]</a></sup>. The part I'm hesitant about is:
```
"By default, xfer jobs get 2GB of memory allocated. The memory footprint scales
somewhat with the size of the file, so if you're archiving larger files,
you'll need to request more memory."
```
Most of the tar archives are in 64GB or 128GB sizes. I'm not sure if a user who just wants to download some model output would know how much memory is needed. I don't even know myself. The same question holds for archiving/uploading the data as well.

**Comment by matthewhoffman** [comment]
@zshaheen , I've used the transfer queue in the past for 500GB+ transfers without a problem.  I added 
```
#SBATCH --mem=10GB
```
to my submit script, based on the documentation:

> You can do this by adding #SBATCH --mem=XGB to the above script (where X in the range of 5 - 10 GB is a good starting point for large files).

Might be worth exploring at some point in the future.

**Comment by golaz** [comment]
@matthewhoffman,

I have used the xfer queue in the past. It works and that is definitely an option that could be added to the best practices documentation page (you are welcome to do so if you'd like).

The main reason I have not been using for most archiving tasks is the wall clock limit of 48 hours. For moderately-sized archiving jobs, 48 hours should be sufficient. But for really large archiving tasks, it won't be.

Also, we do not recommend running zstash on edison or cori login nodes, but rather on the data transfer nodes (DTN) which offer better performance.

**Comment by golaz** [comment]
Closing now. The currently recommended E3SM best practices is to archive from NERSC data transfer nodes using zstash from the E3SM unified environment. A 'screen' session is recommended for long archival tasks.
