### ISSUE TITLE
Update release process to use conda-forge

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zstash#251]
Update GitHub Actions and https://e3sm-project.github.io/zstash/_build/html/main/dev_guide/release.html#releasing-on-anaconda to reflect the new conda-forge process (see https://github.com/conda-forge/staged-recipes/pull/21883).

From @xylar: we would need to remove the GitHub actions that make the build for the `e3sm` anaconda channel.  Then, you would change the sections about `anaconda` to instead refer to waiting for a bot PR to come up automatically on conda-forge after the GitHub release.  A maintainer would then update the dependencies on conda-forge to match the `conda/meta.yaml` file for the GitHub release and merge the conda-forge PR.

**Comment by xylar** [comment]
It is time to make these changes (before the next release), now that there is a zstash feedstock:
https://github.com/conda-forge/zstash-feedstock/
