### ISSUE TITLE
Prompted for login info when running hsi at Livermore Computing (LC)

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/zstash#26]
When trying to run `zstash` on the LC machines, we get prompted for a `Principal` and `OTP`. This isn't ideal and I'll see if there's a way around this.

**Comment by golaz** [comment]
I believe @tangq has been using ztsash on LC. You may want to check with him to see how it performs.

**Comment by zshaheen** [comment]
After a few phone calls and emails with Livermore Computing, I'm able to use `hsi`. Testing v0.2.0 of zstash works on oslic, the dedicated DTN.

---

The issue was that as an intern, my LC account had restricted zone (RZ) access. Due to this, I was asked for some login information for my non-existent RZ token when using `hsi`. Also with an RZ account, you're supposed to move the data from it's HPSS to another location, then to someplace where everyone can access it.

After calling (more than four times), I was able to successfully remove my RZ access and could access HPSS normally.

This is probably an issue that others will not experience.
