### ISSUE TITLE
Print version number

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#27]
Add option to print zstash version number. At a minimum as part of

`zstash -h`

**Comment by zshaheen** [comment]
This was done in e38c12003970228abb5a0608f686fa2f55a8f085.

When a user runs `zstash -h`, the below is seen.
```
$ zstash -h
usage: For v0.3.0, zstash <command> [<args>]

Available zstash commands:
  version    print the version of zstash
  create     create new archive
  update     update existing archive
  extract    extract files from archive
  chgrp      change the group of an archive
  check      check the integrity of the files in the archive
  ls         list the files in an archive

For help with a specific command
  zstash command --help

positional arguments:
  command     command to run (create, update, extract, ...)

optional arguments:
  -h, --help  show this help message and exit
```

We've also added the `version` argument, which prints the version. 
```
$ zstash version
v0.3.0
```
Usually, we'd have `zstash -V`, but a positional command (`create`, `extract`, etc) is required . Trying to work around this would make this more complex than needed.
