### ISSUE TITLE
`testLsGlobus` hangs on Perlmutter

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zstash#299]
`testLsGlobus` hangs on Perlmutter. I ran the zstash unit tests using Unified 1.9.0 on Chrysalis, Compy, and Perlmutter. All tests pass except for `testLsGlobus` on Perlmutter. That test hangs.

https://app.globus.org/activity shows "warning: connection failed" for "zstash_test index" and "zstash_test 000000".

Example event log:
```
{
  "context": [
    {
      "endpoint": "NERSC Cori (9d6d99eb-6d04-11e5-ba46-22000b92c6ec)",
      "operation": "Endpoint Scan"
    }
  ],
  "error": {
    "details": "Error (connect)\nEndpoint: NERSC Cori (9d6d99eb-6d04-11e5-ba46-22000b92c6ec)\nServer: dtn05.nersc.gov:2811\nMessage: Could not connect to server\n---\nDetails: globus_xio: Unable to connect to dtn05.nersc.gov:2811\\nglobus_xio: System error in connect: Connection refused\\nglobus_xio: A system call failed: Connection refused\\n\n",
    "type": "GSHError"
  }
}
```

Reproduction steps:
```
# Follow (c) directions on https://e3sm-project.github.io/zstash/_build/html/main/dev_guide/release_testing.html

$ git fetch upstream main
$ git checkout -b test_unified_1.9.0_pm upstream/main
$ git log # check the commits match https://github.com/E3SM-Project/zstash/commits/main

$ source /global/common/software/e3sm/anaconda_envs/load_latest_e3sm_unified_pm-cpu.sh

$ python -m unittest tests/test_globus.py
```

**Comment by forsyth2** [comment]
I don't _think_ this issue is related to #298, since the error there is "Consent required" rather than "Could not connect to server".

@mahf708 @chengzhuzhang @golaz If possible, can one of you confirm this also happens for you? That way, we can determine if it is a me-specific problem. Thanks. 

@xylar FYI -- I ran all tests for `zppy` and `zstash` on the released Unified 1.9.0. This is the only test that has given me an issue.

**Comment by xylar** [comment]
@forsyth2, it the problem that it's referring to Cori (which is gone) as the endpoint?

**Comment by forsyth2** [comment]
> it the problem that it's referring to Cori (which is gone) as the endpoint?

I thought the Cori and Perlmutter endpoints were identical??

> Details: Error: '~/zstash_test' not found

Interesting. That directory should be created by the test...

**Comment by tylern4** [comment]
The Perlmutter endpoint is different from the (former) Cori endpoint. Last week Wednesday (09/13) we upgraded the DTN hardware and Globus endpoints which removed the old Cori endpoint. At NERSC we currently have 3 endpoints.

- [NERSC DTN](https://app.globus.org/file-manager/collections/9d6d994a-6d04-11e5-ba46-22000b92c6ec/overview) For accessing the Community File System (CFS) and home directories. GCSv5
- [NERSC Perlmutter](https://app.globus.org/file-manager/collections/6bdc7956-fc0f-4ad2-989c-7aa5ee643a79/overview) Primarily for accessing Perlmutter scratch, but also access to CFS and homes. GCSv5
- [NERSC HPSS](https://app.globus.org/file-manager/collections/9cd89cfd-6d04-11e5-ba46-22000b92c6ec/overview) For accessing HPSS at NERSC. This is still the older Globus version GCSv4 but will soon be upgraded to GCSv5.

For the GCSv5 endpoints my guess is the tests will fail with the `data_access` consent error similar to #298

**Comment by forsyth2** [comment]
Thanks for the info. Yes, the error message today is different in fact: "No such endpoint"
```
python -m unittest tests/test_globus.py
Removing test files, both locally and at the HPSS repo
E
======================================================================
ERROR: testLs (tests.test_globus.TestGlobus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/u1/f/forsyth/zstash/tests/test_globus.py", line 184, in testLs
    self.helperLsGlobus(
  File "/global/u1/f/forsyth/zstash/tests/test_globus.py", line 161, in helperLsGlobus
    self.preactivate_globus()
  File "/global/u1/f/forsyth/zstash/tests/test_globus.py", line 69, in preactivate_globus
    r = self.transfer_client.endpoint_autoactivate(ep_id, if_expires_in=600)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0_login/lib/python3.10/site-packages/globus_sdk/services/transfer/client.py", line 458, in endpoint_autoactivate
    return self.post(
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0_login/lib/python3.10/site-packages/globus_sdk/client.py", line 166, in post
    return self.request(
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.0_login/lib/python3.10/site-packages/globus_sdk/client.py", line 321, in request
    raise self.error_class(r)
globus_sdk.services.transfer.errors.TransferAPIError: ('POST', 'https://transfer.api.globus.org/v0.10/endpoint/9d6d99eb-6d04-11e5-ba46-22000b92c6ec/autoactivate?if_expires_in=600', 'Bearer', 404, 'ClientError.NotFound', "No such endpoint '9d6d99eb-6d04-11e5-ba46-22000b92c6ec'", 'fFV8oi6AO')

----------------------------------------------------------------------
Ran 1 test in 1.608s

FAILED (errors=1)
```

**Comment by forsyth2** [comment]
I set the endpoint to be the Perlmutter one rather than the Cori one, as follows:
```
$ cat ~/.zstash.ini
[local]
globus_endpoint_uuid = 6bdc7956-fc0f-4ad2-989c-7aa5ee643a79
```

I now get `ERROR: ('POST', 'https://transfer.api.globus.org/v0.10/transfer', 'Bearer', 403, 'ConsentRequired', 'Missing required data_access consent', 'MBQbd1G1n')`, which is indeed the error in #298. So, I'll close this issue.
