### ISSUE TITLE
Suggestion: Document that zstash create won't create a sub-directory 

### ISSUE THREAD

**Issue by cameronsmith1** [E3SM-Project/zstash#30]
Suggestion: In documentation for zstash create: mention that it won't create a sub-directory in the directory specified by --hpss, ie the user must include the sub-directory they want in the --hpss specification.

**Comment by zshaheen** [comment]
@golaz, this seems like a good point. It's up to your discretion if you want to make a note of this, [probably here where you talk about `<local_path>`](https://e3sm-project.github.io/zstash/docs/html/usage.html#create).

**Comment by cameronsmith1** [comment]
Per our conversation in https://github.com/E3SM-Project/zstash/issues/32, I am using v0.2.0, however I cannot seem to update to v0.3.0

**Comment by golaz** [comment]
The documentation has been updated to indicate that the HPSS path should be unique for each zstash archive.
