### ISSUE TITLE
Suggestion: Modify zstash check, to state if the checks are all OK.

### ISSUE THREAD

**Issue by cameronsmith1** [E3SM-Project/zstash#31]
Suggestion: Modify zstash check, to have a clear statement at the end if the checks are all OK.

All I got at the end of my 'zstash check' was:

```
DEBUG: Closing tar archive zstash/000006.tar
DEBUG: Closing index database
```

**Comment by zshaheen** [comment]
As you can see [in `check.py`](https://github.com/E3SM-Project/zstash/blob/master/zstash/check.py), it does exactly what extract does (which includes the checking), but doesn't keep any files. Looking at the [latest code for `extract.py` you can see that we have a message displayed](https://github.com/E3SM-Project/zstash/blob/master/zstash/extract.py#L197).

All you need to do is upgrade your version of `zstash` to v0.3.0. Please see the documentation website for more information.
