### ISSUE TITLE
How to determine the version of zstash being used?

### ISSUE THREAD

**Issue by cameronsmith1** [E3SM-Project/zstash#32]
Is there a way to determine the version of zstash being used? 

This can be particularly useful to (i) know that the version being used is the latest, and (ii) reporting errors.

I could not find this in the documentation, and guessing at arguments, such as --version, didn't work for me.

**Comment by zshaheen** [comment]
Yes, there is:

```
$ zstash version
```

Hmm, [this error message defined by `usage`](https://github.com/E3SM-Project/zstash/blob/master/zstash/main.py#L22) should have been printed when asking for help. It must mean that you have a version older than `v0.3.0`.

With an older version (or even the most recent version), I think you can check the version like so:
```
python -c 'import zstash; print(zstash.__version__)'
```

---

The reason as to why `zstash -v` or `zstash --version` doesn't work is due to the way users already interact with the software, via `zstash <command>`. I guess we can have a special case where if `zstash -v` or `zstash --version` is given, just print the version. However, the current parser expects the format to be `zstash <command> [<args>]`.

**Comment by cameronsmith1** [comment]
That syntax is fine with me.  However, it would be good to add it to the list of commands discussed on the usage page (https://e3sm-project.github.io/zstash/docs/html/usage.html).

Your python command says that I am using v0.2.0 (I am working on Cori at NERSC).   However, when I try to update using the command given in the installation documentation ```conda update zstash -c e3sm -c conda-forge``` (https://e3sm-project.github.io/zstash/docs/html/installation_and_updating.html) it outputs the following, but leaves me with v0.2.0:

```
(zstash_env) pjc@cori03:~> conda update zstash -c e3sm -c conda-forge
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.4.7
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base conda

# All requested packages already installed.
```

When I try to update conda using ```conda update -n base conda```, it does a bunch of stuff but ultimately fails because of a lack of permissions.

**Comment by zshaheen** [comment]
I'm not sure why that's no longer working, as you can see, [we have v0.3.0 in the `e3sm` channel on Anaconda](https://anaconda.org/e3sm/zstash/files). I guess for your own sake, you can just create a new env from scratch, making sure that you get the latest version.

However, this should be investigated.

**Comment by cameronsmith1** [comment]
The zstash instructions for Cori (https://e3sm-project.github.io/zstash/docs/html/installation_and_updating.html) say to load python-2.7 and zstash_env, which is what I was doing.  When I load the e3sm_unified environment I get zstash v0.3.0.

Do the instructions just need to be updated?

**Comment by zshaheen** [comment]
> Pinging @golaz to make him aware of this discussion.

Yes, good idea. I don't work at LLNL anymore. ¯\\\_(ツ)_/¯

**Comment by cameronsmith1** [comment]
Thank you for staying engaged and moving this forward :-).

**Comment by cameronsmith1** [comment]
For updating the installation documentation (https://e3sm-project.github.io/zstash/docs/html/installation_and_updating.html), would the easiest thing be to point to the e3sm_unified instructions (although not everyone has access to the E3SM Confluence pages)?

**Comment by chengzhuzhang** [comment]
@cameronsmith1 Thanks for the suggestion! Using `e3sm_unified` will be the most straightforward approach to use `zstash` . I'm happy to help update the installation doc by adding a section `to use zstash via e3sm_unified`. But please us know if you encounter issues specific to run it in the `e3sm_unified`.

**Comment by cameronsmith1** [comment]
Thanks for your help, @chengzhuzhang .  On the basis of the recent discussions on this issue and https://github.com/E3SM-Project/zstash/issues/30, I think there are 3 opportunities to improve the documentation for zstash:

1. Update the installation & update instructions to include e3sm_unified.
2. Add 'zstash version' to the usage page.
3. For 'zstash create', clarify that the argument to --hpss should include the sub-directory the user wants to put the tar files into.

**Comment by golaz** [comment]
@cameronsmith1 : thanks for your suggestions. I have now updated the documentation to include the changes you suggested.
