### ISSUE TITLE
Delete tar option

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/zstash#33]
I feel it is useful to have the delete tar file option when extract or check with zstash. This function is particularly useful for simulations with large data size. I recently ran an ensemble simulations. Each member has over 30 tar files. Checking them almost used up all my scratch space.

**Comment by golaz** [comment]
This has been merged: https://github.com/E3SM-Project/zstash/commit/1961c45aad02fc03377e714c6766e9fb7241d55f
