### ISSUE TITLE
md5sum vs hashlib

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/zstash#36]
I recently had to hash a large number of mpaso files, and found that using the "md5sum" cli tool was about 3x faster then the hashlib method used by zstash. Not a huge difference since most of the time zstash is waiting on hsi, but it would be fairly simple to replace the current hashlib method with calls to the md5sum utility.

**Comment by golaz** [comment]
Interesting; I was not aware of that. For zstash, I implemented a streaming model that adds file to the tar file at the same time as it computes the md5sum. This considerably reduces I/o as it avoids reading the entire file twice (once for hashing and once for tarring). That is something that can be implemented quite simply with hashlib, but I don't think it could be done with the command line md5sum. In my tests, the streaming approach was substantially faster than doing two separate steps. But maybe I should redo some timing tests.

**Comment by sterlingbaldwin** [comment]
That makes sense. I didnt realize it was skipping a step by not writing out twice, this is probably the better approach I just happened to notice that for doing hashes one file at a time that md5sum was faster but it might not work for file chunks in memory.
