### ISSUE TITLE
Extracting Simulations on NERSC

### ISSUE THREAD

**Issue by eroesler** [E3SM-Project/zstash#37]
Hi,  
I'm trying to extract high resolution simulations stored on NERSC:
/global/cscratch1/sd/acmedata/E3SM_simulations/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG/

into my scratch space:
/global/cscratch1/sd/eroesler/e3sm_viz 

Following the github io, I've loaded the latest e3sm unified environment on NERSC.   
I try to query the zstash log for where the files are via zstash ls $path_to_data, but I get errors.   I've tried pointing with the flag --hpss, too.

**Comment by beharrop** [comment]
Hi @eroesler , HPSS is down today for maintenance (https://www.nersc.gov/users/live-status/).  I was also trying to run zstash this morning, unsuccessfully, when I realized that.

**Comment by eroesler** [comment]
Hi @beharrop :  Thanks!  I didn't see that.  I'm trying again this afternoon but no luck getting connected to the data transfer nodes.

**Comment by tangq** [comment]
@eroesler , I happen to archive some simulations now. dtn02 and dtn03 are working fine for me. Which dtn node did you try?

**Comment by eroesler** [comment]
Hi @tangq :  It was dtn01.   I'll try those others!  Thank you, I didn't know they existed!

**Comment by eroesler** [comment]
@beharrop :  Can you please advise on if I need to run interactively on the data nodes to extract?
Is this possible on a data transfer node?   https://docs.nersc.gov/jobs/interactive/

From $mydir, I'm trying to extract the ocn directory:

zstash extract --hpss=2019/E3SM_simulations/HR_paper/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG ocn/*

And get 
EBUG: stderr:
b'Generating .netrc entry...\nMust run interactively to update .netrc\nUnable to update .netrc file\nFor help, see http://www.nersc.gov/nusers/systems/hpss/accounts_passwords.php\n'

**Comment by tangq** [comment]
You don't need to run interactively. You can find step-by-step instructions on how to retrieve data using zstash on data transfer nodes on [this page](https://acme-climate.atlassian.net/wiki/spaces/ED/pages/668959422/v1+DECK+output+HPSS+archive).

It seems you are trying to extract some files I archived...

After sourcing the e3sm unified env, try this
`zstash extract --hpss=/home/t/tang30/2019/E3SM_simulations/HR_paper/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG "*/ocn/*"`

**Comment by beharrop** [comment]
The zstash documentation is quite good.  They have a "best practices" page (https://e3sm-project.github.io/zstash/docs/html/best_practices.html) that pretty much walks through the step-by-step process for all of the basics.

**Comment by eroesler** [comment]
@tangq :  Thank you for posting this and your help.  
The error prevails with guidance to run interactively.  I'm following the guide on github:  
https://e3sm-project.github.io/zstash/docs/html/best_practices.html#nersc

Was the Confluence page created before the guide?  There's information about installing zstash, but from the guide, is it loaded with e3sm_unified?    

Here's my step-by-step.... I'm probably missing something:

`$ ssh dtn02.nersc.gov
$ screen
$ bash
$ source /global/project/projectdirs/acme/software/anaconda_envs/load_latest_e3sm_unified.sh
$ cd /global/cscratch1/sd/eroesler
$  zstash extract --hpss=/home/t/tang30/2019/E3SM_simulations/HR_paper/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG "*/ocn/*"
`

**Comment by beharrop** [comment]
I get the following when I run the same commands as you.

`DEBUG: Opening index database
INFO: Transferring from HPSS: zstash/index.db
DEBUG: Running zstash extract
DEBUG: Local path : /global/cscratch1/sd/acmedata/E3SM_simulations/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG
DEBUG: HPSS path  : /home/t/tang30/2019/E3SM_simulations/HR_paper/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG
DEBUG: Max size  : 274877906944
DEBUG: Keep local tar files  : False
DEBUG: Closing index database
INFO: No failures detected when extracting the files.
`

It looks to have run successfully, but did not find any files matching the expression "*/ocn/*".  Are you getting the same thing?

**Comment by beharrop** [comment]
If I change the command to `zstash extract --hpss=/home/t/tang30/2019/E3SM_simulations/HR_paper/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG "*ocn/*"`, then it begins downloading 000037.tar.   I'm not sure what I am getting with that, but maybe there is something amiss with the naming structure that would solve your problem....

**Comment by eroesler** [comment]
@beharrop :  Thanks for rerunning those commands.   I'm at a loss... 

I've tried Qi's command:
``$ zstash extract --hpss=/home/t/tang30/2019/E3SM_simulations/HR_paper/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG "*/ocn/*"``

And an earlier one listed above:
``$ zstash extract --hpss=2019/E3SM_simulations/HR_paper/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG "*/ocn/*"``

Both commands throw the error:
``
DEBUG: Opening index database
INFO: Transferring from HPSS: zstash/index.db
ERROR: Transferring file from HPSS: index.db
DEBUG: stdout:
b''
DEBUG: stderr:
b'Generating .netrc entry...\nMust run interactively to update .netrc\nUnable to update .netrc file\nFor help, see http://www.nersc.gov/nusers/systems/hpss/accounts_passwords.php\n'
Traceback (most recent call last):
  File "/global/project/projectdirs/acme/software/anaconda_envs/cori/base/envs/e3sm_unified_1.3.0/bin/zstash", line 11, in <module>
    load_entry_point('zstash==0.3.0', 'console_scripts', 'zstash')()
  File "/global/project/projectdirs/acme/software/anaconda_envs/cori/base/envs/e3sm_unified_1.3.0/lib/python3.7/site-packages/zstash-0.3.0-py3.7.egg/zstash/main.py", line 50, in main
  File "/global/project/projectdirs/acme/software/anaconda_envs/cori/base/envs/e3sm_unified_1.3.0/lib/python3.7/site-packages/zstash-0.3.0-py3.7.egg/zstash/extract.py", line 113, in extract
  File "/global/project/projectdirs/acme/software/anaconda_envs/cori/base/envs/e3sm_unified_1.3.0/lib/python3.7/site-packages/zstash-0.3.0-py3.7.egg/zstash/hpss.py", line 66, in hpss_get
Exception ``


Could it be something in your environments that is different?

**Comment by tangq** [comment]
The confluence page created after the guide and relies on e3sm unified envs, so no need for every user to install zstash.

Without "*", it tries to file the exact matching of "/ocn/", which doesn't exist.

**Comment by eroesler** [comment]
Hmmm...I've got the stars and quotes in there, just like you listed above.

**Comment by tangq** [comment]
Can you remove the zstash folder and try again?

**Comment by eroesler** [comment]
Same error as before after removing....

Out of curiosity, do you get these errors when you source the e3sm_unifed environment?

``$source /global/project/projectdirs/acme/software/anaconda_envs/load_latest_e3sm_unified.sh
module swap PrgEnv-intel PrgEnv-gnu
bash: module: command not found
module unload craype-hugepages2M
bash: module: command not found``

**Comment by tangq** [comment]
I got these module errors in recent a couple of days. It also seems varying by login nodes.

**Comment by tangq** [comment]
Um...interesting. Your error suggests that the error happens when retrieving zstash/index.db.

I would suggest logging out and logging in with a new terminal, then trying from a new folder.

Same commands seem working for @beharrop and me..

**Comment by beharrop** [comment]
Yes, I get those same errors too when I source e3sm_unified on the data transfer nodes.  I have also used zstash on the regular cori login, at which point I get no such errors.  The transfers are slower, but not by much in my experience.  Perhaps you could try using the login node just to see if it's something weird with the DTNs.

**Comment by golaz** [comment]
@eroesler:

I get the same error as you do when activating the E3SM unified environment on the dtn. These errors are new. I used the unified environment earlier this week without seeing them. However, the errors appear to be harmless and not affect zstash. The following commands work for me

`zstash ls --hpss=/home/t/tang30/2019/E3SM_simulations/HR_paper/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG "*ocn/*"`

and

`zstash extract --hpss=/home/t/tang30/2019/E3SM_simulations/HR_paper/theta.20180906.branch_noCNT.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG "*ocn/*" `

starts to retrieve 000037.tar as @beharrop  mentioned above.

To make sure your syntax is correct, try first `zstash ls`. This will list the files that match your query. If those are the files you want to retrieve, then use exactly the same command replacing `ls` with `extract`.

**Comment by eroesler** [comment]
Thank you for the help and feedback.   I'm still getting errors with logging-out and back in, not using screen, using the login-nodes, and trying in a different directory.   

The ``zstash ls`` command is not even getting the index.db and crashing there:  ``ERROR: Transferring file from HPSS: index.db``

What do your environments look like when you're on Cori's login nodes?    This might be our differences?

**Comment by tangq** [comment]
I use default environments on NERSC, no special changes.

**Comment by tangq** [comment]
@eroesler , any luck? If you still have issues, you may want to open an issue with the link [here](https://e3sm-project.github.io/zstash/docs/html/support.html). The developer of zstash will be able to provide more help.

**Comment by eroesler** [comment]
@golaz figured it out!    He said, "Type ``hsi`` into the command line on the login-node."   It asked me for a password + OTP.  He said that it should not do that and to submit a ticket.   

In looking at storage at NERSC, I found the following information: 
https://docs.nersc.gov/filesystems/archive/#automatic-token-generation
_"The first time you try to connect from a NERSC system (Cori, DTNs, etc.) using a NERSC provided client like hsi, htar, or pftp you will be prompted for your NERSC password + one-time password which will generate a token stored in $HOME/.netrc. After completing this step you will be able to connect to HPSS without typing a password..."__

This solves the error messages including the one about asking for an interactive session on .netrc.   I now see a statement saying ``INFO: Transferring from HPSS: zstash/000037.tar``

Thank you for your help in figuring this out.
