### ISSUE TITLE
'ls' works without the /archive at the end of the path, but then the 'extract' will fail

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/zstash#38]
When listing a set of files with an hpss path such as "/home/m/maltrud/E3SM/20181217.BCRC_CNPCTC20TR_OIBGC.ne30_oECv3.edison," zstash will happily list out the contents of the archive, but then if you try and run the same command with "extract" it will fail (it works fine if you use the path /home/m/maltrud/E3SM/20181217.BCRC_CNPCTC20TR_OIBGC.ne30_oECv3.edison/archive). Zstash should probably either:

a) not list the files without the /archive, or
b) extract the files without the /archive.

**Comment by zshaheen** [comment]
Can you go to another directory and try the same zstash extract command, without doing an ls? Does that work?

**Comment by sterlingbaldwin** [comment]
I'll try wiping the zstash directory between the `ls` and the `extract` to see what happens, but regardless this is an unexpected behavior. Regardless, I would think that it should behave similarly with both commands on the same path.

**Comment by golaz** [comment]
I could not reproduce the behavior. On NERSC:

```
source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh
cd /global/cscratch1/sd/golaz/tmp
zstash ls --hpss=/home/m/maltrud/E3SM/20181217.BCRC_CNPCTC20TR_OIBGC.ne30_oECv3.edison
INFO: Transferring file from HPSS: zstash/index.db
ERROR: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/m/maltrud/E3SM/20181217.BCRC_CNPCTC20TR_OIBGC.ne30_oECv3.edison; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`.
```
zstash correctly reports an error when it cannot find the file.
