### ISSUE TITLE
sqlite3.OperationalError: disk I/O error on NERSC cfs file systetm

### ISSUE THREAD

**Issue by minxu74** [E3SM-Project/zstash#41]
On NERSC cfs system, there was an error when running zstash on the NERSC cfs file system.  The reason should be caused by the file system. Will it be possible to let users define the location of zstash directory instead of the default one under local path?

```
DEBUG: Running zstash create
DEBUG: Local path : /global/cfs/cdirs/cmip6/temp_trans/20191123.CO21PCTRAD_RUBISCO_CNPCTC20TR_OIBGC.I1900.ne30_oECv3.compy
DEBUG: HPSS path  : E3SM_simulations/20191123.CO21PCTRAD_RUBISCO_CNPCTC20TR_OIBGC.I1900.ne30_oECv3.compy
DEBUG: Max size  : 274877906944
DEBUG: Keep local tar files  : False
DEBUG: Making sure input path exists and is a directory
DEBUG: Creating target HPSS directory
DEBUG: Making sure target HPSS directory exists and is empty
DEBUG: Creating local cache directory
DEBUG: Creating index database
Traceback (most recent call last):
  File "/global/cfs/cdirs/acme/software/anaconda_envs/base/envs/e3sm_unified_1.3.0/bin/zstash", line 11, in <module>
    load_entry_point('zstash==0.3.0', 'console_scripts', 'zstash')()
  File "/global/cfs/cdirs/acme/software/anaconda_envs/base/envs/e3sm_unified_1.3.0/lib/python3.7/site-packages/zstash-0.3.0-py3.7.egg/zstash/main.py", line 46, in main
  File "/global/cfs/cdirs/acme/software/anaconda_envs/base/envs/e3sm_unified_1.3.0/lib/python3.7/site-packages/zstash-0.3.0-py3.7.egg/zstash/create.py", line 115, in create
sqlite3.OperationalError: disk I/O error
```

**Comment by minxu74** [comment]
It seemed  to be a common problem for sqlite files stored in the NFS or journal file systems.

**Comment by rljacob** [comment]
@minxu74 do you have a pointer to something discussing this issue with sqlite files?

**Comment by golaz** [comment]
Currently, zstash does not have an option to specify an alternate location for storing local cache files.
Could it be that zstash is failing in this case because you do not have write permission?

**Comment by minxu74** [comment]
@rljacob please find some discussions in the following links:
https://stackoverflow.com/questions/47540607/disk-i-o-error-with-sqlite3-in-python-3-when-writing-to-a-database
https://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible
https://stackoverflow.com/questions/29244788/error-disk-i-o-error-on-a-newly-created-database
https://stackoverflow.com/questions/9993555/disk-i-o-error-with-sqlite

But I found the reason with the reminder from @golaz. I do have the write permission under the directory and also I can create new files larger than (200MB) in that directory, but the disk quota  already exceeded when I was running zstash.  So the file system lets you create normal files like netcdf or text files, but does not allow you to create sqlite db files when the disk quota exceeds.

@golaz Thanks for your comment. I figured out the cause (please see above). It will be very helpful for zstash to have the option to provide alternative location in some situations.

**Comment by golaz** [comment]
@minxu74 : thanks, that explains the error. I opened up a new issue (https://github.com/E3SM-Project/zstash/issues/43) for the possibility to specify an alternate location for local zstash files.

Additional discussion should go there. There would be pros and cons for doing so.
