### ISSUE TITLE
Option to specify alternate location for local zstash files

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#43]
Currently, zstash will store local copies of database and tar files under the sub-directory `zstash/`.

In certain cases (see for example https://github.com/E3SM-Project/zstash/issues/41), it might be useful to have the flexibility to specify and alternate location, maybe with a new command line argument:

`--cache=...`

Is this worth considering implementing? Or would it just add unnecessary confusion?

**Comment by golaz** [comment]
Similar suggestion from Tony Bartoletti:

> For the future  . . . it would be nice™ if zstash accepted specific paths for the zstash tarfiles and the location of file extractions.  Hence, rather than
>
>                (required PWD parent to zstash/ tars and index.db)
> 
>                zstash extract <file_path_patterns>  (with extracted paths destined for PWD/)
>
> it could accept 
> 
>                zstash extract --zstash-dir /p/user_pub/e3sm/archive/1_0/20180316.DECKv1b_A1.ne30_oEC.edison/  --extract-dir  <anyplace at all>
> 
> This would:
> 
> 1.  Allow us to execute the”zstash” command from any location or script
> 
> 2.  (most importantly) Free us from having to structure the E3SM “archive” directories such that each have a “zstash” subdirectory.
> 
> 3.  Additional file movement (e.g. to staging) would be unnecessary.
> 
> Wishful thinking?  😉

**Comment by rljacob** [comment]
This is definitely worth doing.

**Comment by forsyth2** [comment]
We'll include the `--extract-dir` option in a separate issue/PR.

**Comment by forsyth2** [comment]
#69 covers the `--extract-dir` option.
