### ISSUE TITLE
Update Zstash to run on macOS

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zstash#51]
The command `display_mode = "stat --format '%a' {}".format(file_path).split()` added in `hpss.py` in #42 only works on Linux. There needs to be a different command for macOS.

**Comment by forsyth2** [comment]
@golaz @chengzhuzhang I'm assuming most people use Zstash on Linux, but let me know if we should try to get this into v0.4.0 (or it might need to be v0.4.1).

**Comment by golaz** [comment]
This can be part of a future release. Instead of relying on an external call, is it possible to rewrite this using Python built-in `os.stat()` function?

**Comment by forsyth2** [comment]
Officially, `zstash` does not support macOS. However, it would still be nice to change the command to use `os.stat`
