### ISSUE TITLE
zstash check deleting local tar file

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#53]
I thought we fixed this, but maybe not completely or it came back?

I'm running zstash on compy (without HPSS). `zstash create` worked fine, but `zstash check` deletes the files after checking is done. Here is what I did:

```
module load anaconda3/2019.03
source /share/apps/anaconda3/2019.03/etc/profile.d/conda.sh
conda activate zstash_env
cd /compyfs/gola749/E3SM_simulations/20191216.alpha20.piControl.ne30_r05_oECv3_ICG.compy
mkdir zstash
zstash create --hpss=none  --maxsize 128 . 2>&1 | tee zstash/zstash_create_20200224.log
zstash check --workers=2 2>&1 | tee zstash/zstash_check_20200226.log
```

I wonder whether it has to do with the fact that I'm not specifying `--hpss=none` on the command line the second time around, instead relying on what is stored in the database. We need to fix this urgently and make sure we have tests catch this.

**Comment by forsyth2** [comment]
@golaz can you specify which files are being deleted?
I created a directory and ran the following from there:
```
