### ISSUE TITLE
Support for replicas

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/zstash#60]
I think that it's possible for `zstash` to support another HPSS repository/directory
to store data in. This would greatly help in diagnosing/averting the data
corruption problem that I'm guessing is still exhibited.

## Current Schema

| `config` Table |
| -------------- |
| [PK] arg (text) |
| value (text) |

| `files` Table |
| ------------- |
| [PK] id (int) |
| name (text) |
| size (int) | 
| mtime (timestamp) |
| md5 (text) |
| tar (text) |
| offset (int) |

## Modifications
I think that the another config should be added to the `config` table, like `replica_dir`, which is just another HPSS path. If I recall, NERSC has another HPSS directory that ensures that the data is stored on a physically separated tape. You'll need to verify this. I'm not sure about other sites.

Then you can expand the `files` table to include `replica_md5` and `replica_tar` columns or something. They are the MD5 hash of the file, as well as the tar that's in `replica_dir`.

| `files` Table |
| ------------- |
| [PK] id (int) |
| name (text) |
| size (int) | 
| mtime (timestamp) |
| md5 (text) |
| tar (text) |
| offset (int) |
| **replica_md5 (text)** |
| **replica_tar (text)** |

### Writing

When writing, we began with `000000.tar` and enumerated ascending.
To create the `replica_tar`, we can start from `FFFFFF.tar` and descend. This differentiation is needed cause all of the tars are stored in a single folder.

So some sample rows would be:

```
1|something.nc|<size>|<mtime>|<md5>|000000.tar|<offset>|<replica_md5>|FFFFFF.tar
2|something_else.nc|<size>|<mtime>|<md5>|000000.tar|<offset>|<replica_md5>|FFFFFF.tar
3|something_else_too.nc|<size>|<mtime>|<md5>|000000.tar|<offset>|<replica_md5>|FFFFFF.tar
4|something2.nc|<size>|<mtime>|<md5>|000001.tar|<offset>|<replica_md5>|FFFFFE.tar
5|something2_else.nc|<size>|<mtime>|<md5>|000001.tar|<offset>|<replica_md5>|FFFFFE.tar
```

### Reading

**If during check/extract there's an MD5 issue, you can try to get the file from the `replica_tar` and see if that's valid. Again, the replica tar is stored at another HPSS dir. The replica path is in the `config` table.** This is the main use case of this entire feature.

### Create

We need to have another argument `--replica_hpss`.

```
zstash create --hpss=<path to HPSS> --replica_hpss=<path to a replica HPSS dir> <local path>
```

### Check/Extract

In the command below, the `hpss` argument could support both the original HPSS dir (`--hpss`) as well as the replica one (`--replica_hpss`) since in theory, they should be interchangeable.
And you'd don't want users (who download the data) to really mess around with the replicas, this feature should be abstracted away from them and just "work".

```
$ zstash check --hpss=<path to HPSS> [--workers=<num of processes>] [files]
```

### Update

Like check/extract above, both of the HPSS paths can be used for `--hpss`.

### List

List should actually just list what's in the `--hpss`. So replica HPSS dirs should show what they have, and same with the "regular" HPSS dirs.

---

Again, this is just an idea. So if it's not useful, please feel free to close this issue.

**Comment by golaz** [comment]
@zshaheen : thanks for the suggestion. However, I think implementing this option into zstash would take significant efforts and greatly complicate the code. The best options to deal with possible corruption remain:

1. Run `zstash check`
2. Optionally, duplicate the entire archive if redundancy is required.
