### ISSUE TITLE
Remove keep from config

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zstash#63]
Remove `keep` from the `config`. Doing this will mean tar files won't be kept or removed based on using the `keep` option in an earlier command. (Although it doesn't seem like this is the current behavior anyway).

**Comment by forsyth2** [comment]
See #14 for a broader-scope version of this issue.

**Comment by golaz** [comment]
This would also be the occasion to revisit what is in config, and whether it really needs to be there.
