### ISSUE TITLE
zstash "ls" counterintuitively overloaded 

### ISSUE THREAD

**Issue by TonyB9000** [E3SM-Project/zstash#68]
I issue `zstash ls archive/atm/hist/*cam.h0.1870*`, and these are found in the tar files.
I issue `zstash ls archive/atm/hist/*cam.h0.1871*`, and these are also found in the tar files.
I issue `zstash extract archive/atm/hist/*cam.h0.1870*`, and these are extracted locally to archive/atm/hist.

I issue `zstash ls archive/atm/hist/*cam.h0.1871*`, and these are NO LONGER found.  Why?
I issue `zstash ls archive/atm/hist/*cam.h0*`, and only the previous 1870 files appear.  Why?

Because zstash magically behaves differently when the local archive exists, and will no longer address the tarfiles.  I need to rename the local archive to force zstash to behave as before.

There is no reason to have zstash replicate the system "ls".  The system "ls" works just fine.

Otherwise, we should provide a "tar_ls" to distinguish these.

**Comment by golaz** [comment]
@TonyB9000 : this is another perfect example of wildcards and the shell playing tricks on the user. (Note also that I updated the formatting of your original post to make it less confusing; Github was also playing tricks by replacing * with italics).

The short answer is: **if you use wildcards with zstash ls/extract, always enclose you expression in double quotes (")**. 

Not doing so can lead to unexpected behavior as the shell will try to expand the wildcards before passing the command line arguments to zstash. The shell substitution only takes places if valid matches are found. If not, the shell will simply pass the expression including wildcards to zstash (which will then do the correct thing).

This explains why the command

`zstash ls archive/atm/hist/*cam.h0*`

will behave differently before and after you extracted files. To avoid confusion, simply use

`zstash ls "archive/atm/hist/*cam.h0*"`

and everything will behave the way you expect. There is no magic there.

This is mentioned a couple of times on the documentation page (https://e3sm-project.github.io/zstash/docs/html/usage.html?highlight=wildcard), but admittedly, users probably won't really get the warnings until they fall into the trap a couple of times.
