### ISSUE TITLE
max-size for 'update' based on 'create'

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zstash#9]
Max size value specified during 'create' should carry over to 'update' phase.

**Comment by golaz** [comment]
Verified that this works as intended in 7b526dce41fe865464d16ae9e22783ecfbf92346.

**Comment by matthewhoffman** [comment]
@zshaheen , I believe the instructions for the 'update' phase here:
https://e3sm-project.github.io/zstash/docs/html/best_practices.html#
should be adjusted to remove the --max-size option from the command based on this issue..  When I tried the command as written I received an error saying --max-size was an invalid option.

**Comment by zshaheen** [comment]
@matthewhoffman, I'm reopening this issue and I'll see what's up. Looking at the code, it seems like we don't have a `--maxsize` arg. I'll add it in.

**Comment by matthewhoffman** [comment]
@zshaheen , I think this issue can remain closed, it's just that the instructions linked above need to be updated to remove the --max-size option from the command described for the 'update' phase.

**Comment by golaz** [comment]
@matthewhoffman : thanks for noticing the inconsistency in the documentation. I have now fixed it.
